// Cross-surface interop (CSP §18): the TypeScript SDK, running the real
// reduced wasm surface, must reproduce **byte-identically** a known-answer
// vector generated by the native Rust core. This is the guarantee that the
// wasm path is bindings over the same core, not a divergent reimplementation
// (§16) — identical objects, oids, and signatures across the boundary.

import { describe, expect, it } from 'bun:test';
import {
  buildPrimitiveObject,
  nodeIdHex,
  objectOid,
  verifyPrimitiveObject,
  wireDecode,
  wireEncode,
} from '../src/wasm.js';
import vector from '../test-vectors.json';

function fromHex(h: string): Uint8Array {
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = Number.parseInt(h.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function toHex(b: Uint8Array): string {
  return Array.from(b)
    .map((x) => x.toString(16).padStart(2, '0'))
    .join('');
}

describe('cross-surface interop (native → wasm)', () => {
  it('reproduces the native-generated primitive byte-identically', () => {
    const seed = fromHex(vector.seed_hex);
    const framed = buildPrimitiveObject(
      seed,
      vector.tree_hex,
      vector.parent_hex,
      BigInt(vector.counter),
      BigInt(vector.wall_time),
      vector.subject,
    );
    expect(toHex(framed)).toBe(vector.expected_framed_hex);
    expect(objectOid(framed)).toBe(vector.expected_oid);
    expect(nodeIdHex(seed)).toBe(vector.expected_node_id);
  });

  it('verifies the in-object signature to the native author NodeId', () => {
    const framed = fromHex(vector.expected_framed_hex);
    expect(verifyPrimitiveObject(framed)).toBe(vector.expected_node_id);
  });

  it('round-trips a wire frame through the same MessagePack codec', () => {
    const json = '{"FrontierDigest":{"tips":["aa","bb"]}}';
    const bytes = wireEncode(json);
    const back = JSON.parse(wireDecode(bytes)) as {
      FrontierDigest: { tips: string[] };
    };
    expect(back.FrontierDigest.tips).toEqual(['aa', 'bb']);
  });
});
